name: 'Close stale issues and PRs'
permissions:
  #contents: write # only for delete-branch option
  issues: write
  #pull-requests: write

on:
  schedule:
    - cron: '30 17 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.1.0